development:
  sessions:
    default:
      database: vongole_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:

test:
  sessions:
    default:
      database: vongole_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong

production:
  sessions:
    default:
      database: vongole
      hosts:
        - <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
  