development:
  sessions:
    default:
      database: vongole_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:

test:
  sessions:
    default:
      database: vongole_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong

production:
  sessions:
    default:
      database: vongole
      hosts:
        - alex.mongohq.com:10067
      username: heroku
      password: 733645008b70e51ed20e86ee9ff2c742
        
      options:
        skip_version_check: true
        safe: true
  